### ISSUE TITLE
Suggest adding parents=True to Path.mkdir()

### ISSUE THREAD

**Issue by versatran01** [hristo-vrigazov/mmap.ninja#1]
Unless there's a reason not to, I suggest adding parents=True to mkdir()

**Comment by hristo-vrigazov** [comment]
That's a good suggestion.  It would be convenient when creating a hierarchy.
Since it is your proposal, do you want to make a pull request? 
I don't have any contributing guidelines yet (will add them soon probably), but I think if you fork the project, do your changes on your branch, and open a pull request would be ok, since the change is small and safe.

**Comment by hristo-vrigazov** [comment]
Closed by https://github.com/hristo-vrigazov/mmap.ninja/pull/2

**Comment by hristo-vrigazov** [comment]
Release `0.2.2` contains your changes.
