### ISSUE TITLE
copying with `wrapper_fn`

### ISSUE THREAD

**Issue by ahalev** [hristo-vrigazov/mmap.ninja#13]
Is there a reason why the `copy` call [here](https://github.com/hristo-vrigazov/mmap.ninja/blob/master/python/mmap_ninja/ragged.py#L113-L114) is necessary when `wrapper_fn` is not None?  It seems like it's just for safety; if so is it possible to remove or add a kwarg to remove?

**Comment by hristo-vrigazov** [comment]
Hey @ahalev Thanks for the question! It is not needed, it was added for safety, because one of the most frequent ways people would use `wrapper_fn` is to pass something like `torch.tensor` or similar there, which would result in a warning because the underlying numpy array (which is a section of the memory map on disk) is not writeable. 

I'm guessing your concerns are about performance?

Your suggestion sounds reasonable, people should be able to opt-out of the copy if they are going to only read the array.

**Comment by hristo-vrigazov** [comment]
@ahalev 

I just released a new version `v0.7.0`, which contains such an option for both `Wrapped` and `RaggedMmap` classes. The option is called `copy_before_wrapper_fn`, it is documented here: 
http://microlib.org/mmap_ninja/#open-an-existing-raggedmmap

By default it keeps the current behavior, as otherwise a lot of users would suddenly get a ton of warnings.

**Comment by ahalev** [comment]
Yes it's about performance, there's a lot of overhead in this copy call. That should do it though! It is a little unclear in e.g. the torch documentation what operations are in place so I agree removing it entirely is not a good idea.
