### ISSUE TITLE
memmap disk usage

### ISSUE THREAD

**Issue by mushcatshiro** [hristo-vrigazov/mmap.ninja#19]
hi there, i was searching around for some inspiration of using memmap to speed up my deep learning training efficiency and found your project. to my knowledge, disk usage when converting from the source format to memmap should be equal or less (depending if there are additional metadata that can be stripped away). based on my experience, for openwebtext (from HF) takes 50+GB disk space and converting it to memmap results in ~17GB on disk. however looking at your readme, you warned users that using mmap.ninja that it might not be a good idea to use it if disk space is a concern. i wonder if that is a result of your implementation (taking care of varying size image) or it is something i am missing out?
thanks!

**Comment by hristo-vrigazov** [comment]
Hi, thanks for the question! Depends on **what** you are converting to a mmap. If you are converting some raw numpy arrays or raw string dataset (e.g. using `StringsMmap`), the disk usage should be similar to the original.

In the README, I warn users about disk space usage because one of the most common use cases is converting compressed images (such as `.jpg`) or videos (such as `.mp4`) to memory-mapped format. In your case,  I think `mmap-ninja` should be similar to the original openwebtext dataset in terms of size.

Closing this, but feel free to discuss this more :)
