### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by slerman12** [hristo-vrigazov/mmap.ninja#4]
Can you explain the difference between this and np.saves_compressed -> writing the buffer to memory?

**Comment by hristo-vrigazov** [comment]
Thanks for the question.

With a memory map, you can easily access a random index very quickly (opening the memory map and `__getitem__` are both very fast). With `np.savez_compressed`, then loading into memory, you have a very slow initial loading into memory if the dataset is big, and also you need to be able to fit the dataset into memory. For example, if you are training on a machine with 4 GPUs, and you want to train a different model with a different dataset for each GPU, you would quickly run out of memory if you load the whole dataset for every single model. Memory maps allow you to achieve ultra-fast, almost in-memory speed without actually taking up much memory, utilizing disk space instead.

I am closing the issue, but feel free to continue the discussion here :)

**Comment by slerman12** [comment]
Thanks for the answer. 

Can you tell me also how this compares to pyarrow?

**Comment by hristo-vrigazov** [comment]
pyarrow does not natively support samples of different shapes, to my knowledge, so you would have to write this logic yourself. Also, pyarrow does not support append/extend: https://github.com/apache/arrow/issues/3622

**Comment by slerman12** [comment]
Thank you for your time.

Two more questions I think.
1. Is it fast/slow for storing TO memory compared to np.savez_compressed?
2. Is there any way to index it non-randomly?

I have the same questions about pyarrow actually, if you know.

**Comment by slerman12** [comment]
And is it compatible with video!

**Comment by hristo-vrigazov** [comment]
1. Is it fast/slow for storing TO memory compared to np.savez_compressed?

Not comparable, because the memory map is never loaded into memory fully. Only the sample you need is loaded into memory. For example, if you are training with batch size of 16, then you only need the memory of those 16 images. You don't load the full dataset into memory.

2. Is there any way to index it non-randomly?

What do you mean here? You just index it in the way you index numpy arrays. `mmap[5]` gives you the r-th sample, and so on.


And is it compatible with video!

Yes, of course. The memory map is initialized from a generator that returns samples as numpy arrays. What is the source of these does not matter.  Check this notebook for an example: https://colab.research.google.com/drive/1xMEHbwntgpBfCGfTicXmdbA8UpEowXzW?usp=sharing
