### ISSUE TITLE
How does it compare to pyarrow, hdf5 or lmdb?

### ISSUE THREAD

**Issue by TheShadow29** [hristo-vrigazov/mmap.ninja#6]
Hello, thanks for the great project. Wanted to know how it compares to columnar data formats like pyarrow/ hdf5 / lmdb? Thanks!

**Comment by hristo-vrigazov** [comment]
Hello, sorry for the late response. You may be interested in the discussions surrounding the introductory post in reddit:
https://www.reddit.com/r/MachineLearning/comments/vd1ey0/p_mmap_ninja_speedup_your_training_dramatically/

The short version is, that this is a lightweight library (less than 1k lines), that is more like an extension of numpy's memory map, so that you can append/extend an already existing memory map, and also have elements of different lengths (in numpy you would have to pad every element to the same shape).

`pyarrow` - provides similar functionality, but does not provide support for elements of different lengths out of the box to my knowledge. So you would have to write your own logic where you store the flat buffer, the offsets, and the shapes in different columns in `pyarrow` to achieve the same functionality that `mmap_ninja` already has. In my projects, I usually use `pyarrow` to store tabular data and intermediary data from the different stages. However, I store stuff like images, audio, etc. in `RaggedMmap` and inside the `pyarrow` object just store an index in the memory map.

`hdf5` - In general, I've found that memory-mapping is faster and much simpler to use, since it operates on the usual `npy` arrays. No need for specification, etc. Check this blog post: https://cyrille.rossant.net/moving-away-hdf5/ 

`lmdb` - In LMDB, you have to convert the returned buffer by yourself into a numpy array with the correct shape, because LMDB can store any object and does not assume that you are storing numpy arrays. While in mmap_ninja, the shapes of the different samples are stored in a memory map themselves, and when you do a __getitem__ you don't have to do any conversion, it is directly returned as a numpy array with the correct shape. Another difference is in the dependencies - when using LMDB, you first need some C extensions, while in mmap_ninja the only dependencies are numpy and tqdm (the progress bar)
