### ISSUE TITLE
Getting slower and slower

### ISSUE THREAD

**Issue by nctamer** [hristo-vrigazov/mmap.ninja#8]
Hi! I really love this package! When I started using it this september it made the life so much easier!! but for some reason it started getting slower through time. Today I just realized that after installing it in a new environment, the new version 0.6 made it even slower. Now I reverted back to 0.5.0. Can you replicate the speed issue? I cannot remember what was the fastest version, and there are really huge differences between them

**Comment by hristo-vrigazov** [comment]
Thanks for the issue! I suspect the copying of the sample made it slower. I will try to dig deeper. Could you tell me which class are you using? `RaggedMmap`, `StringsMmap`, or the numpy module?

https://github.com/hristo-vrigazov/mmap.ninja/commit/7a7b50308d26de73a0c08e055fccfae50c040360

**Comment by nctamer** [comment]
Thank you very much for the fast reply!! 
I use only RaggedMmap. Actually both the creation and accessing samples got slower. I have a creation script which is running in a cluster for 25 days now and it doesn't seem to finish anytime soon... (before the same operation took 2 days). But my biggest issue is the read time, before everything was running at an instant, I guess it was the version 0.2.4 which worked smoothly. I will try to revert  to that.

**Comment by hristo-vrigazov** [comment]
That helps a lot! I figured out what the problem as when accessing sampes, it was introduced in 0.5.4, and it was because the sample was copied regardless of whether `wrapper_fn` was passed (in older versions, it never did a copy). . Today I released 0.6.1 which does the copying of a sample only when `wrapper_fn` is passed (this is done to avoid warnings when you do something like `RaggedMmap('out_dir', wrapper_fn=torch.tensor)` about getting an unwritable sample.

Do you pass a `wrapper_fn` argument when you open the `RaggedMmap`? If not, I think the new version should fix the item accessing. 

I am still not sure about the slowing down of the creation, I will try to create benchmarks for it on a small corpus so I could get quick feedback. But a few versions ago I did refactoring and I reused a function, which could be the culprit. I will update you here with the developments. 

Your feedback and inputs are invaluable :) And yes, I think `0.2.4` is safe to use for now, until I am sure it's fixed and have benchmarks to avoid such regressions in the future

**Comment by hristo-vrigazov** [comment]
By the way, you can chat about `mmap-ninja` anytime here: https://app.gitter.im/#/room/#mmap-ninja:gitter.im

You can log in into gitter with your github account.

**Comment by nctamer** [comment]
Thank you very much! I do not use a wrapper, indeed, I take small windowed frames of audio/video from lists of huge arrays, so I only get a fraction of a sample per batch to np.array(sample[segment]). Normally reading a small window from an arbitrary point of an audio file is very costly since you have to at least read to the related segment, i.e., if the segment is at the end of the wav file, you end up opening the entire file of 100MBs. 

The ability of immediately reading and passing only a segment of the mmap array into the memory is really helpful for me. Then I guess it got slow because the copy operation creates the array of from the huge mmap arrays at the moment I access the sample, no? It doesn't keep the sample in the mmap before reading the segment?

**Comment by hristo-vrigazov** [comment]
Yes! So, basically, I added the copying of the sample because otherwise there were PyTorch warnings when passing `torch.tensor` as a wrapper function. However I had added the copying in the wrong place, and it was always making a copy. And since you use the operation so often, the small difference quickly added up to a huge difference.

In version `0.6.1`, the accessing of samples is similar to `0.2.4` in terms of speed. I tested it on the pets image dataset. There, for one iteration over the memory map, `0.2.4` takes ~0.150 seconds, while 0.5.* were taking ~1.20 seconds, so there was a huge difference. `0.6.1` takes again ~0.150 unless you pass a `wrapper_fn`. So I think in terms of accessing it should be fixed now.

I still have not figured out what would be the problem in the creation, but I am investigating it.

By the way, I was just working on parallel initialization, which could probably speed it up even more, but I think it's better to fix the existing issues first, and then will expand with new functionalities.

Maybe you could create a smaller version of your dataset, so you would get a quick estimation of which version is ok for you to use. I think in 0.6.1 the creation will still be slower, but accessing items should be ok now.

**Comment by nctamer** [comment]
Thank you very much!!

**Comment by hristo-vrigazov** [comment]
You're very welcome! I am really happy when I hear feedback from users, means that someone is using it :) If you have any questions, problems, etc. or anything else, do not hesitate to open an issue here, or chat on Gitter.

I will update here once I figure out why the creation has slowed down, and when I release the parallel initialization. 

By the way, one feature in the newer versions of `mmap-ninja` is the lazy creation. For example, you can now do this:

```
from mmap_ninja.ragged import RaggedMmap

ragged = RaggedMmap('out') # This line used to throw an error if the mmap did not exist
ragged.append(np.arange(10)) # This line now will initialize the memory map
```
